version: '3.9'
services:
  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    container_name: url_shortener_redis
    ports:
      - "6379:6379"

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: url_shortener_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener_db
