base62:
  alphabet: '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'

async:
  pools:
    size: 5
    maxSize: 20
    maxQueueCapacity: 500
    taskExecutorPoolPrefix: Task-worker-

unique-number:
  batch: 140
  start: 55_000_000_000
  increment: 155 # должен быть не больше 80% от cache.maxSize ########__

cache:
  maxSize: 200
  percentage: 0.2

cron: '0 0 0 * * *'

